<a href="https://colab.research.google.com/github/srija2771/pytorch2/blob/main/srija/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [2]:
## Introduction to Tensor
###creating sensors

In [3]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#get tensor back as python int
scalar.item()

7

In [6]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#matrix
MATRIX=torch.tensor([[7,8],
                    [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
#tensor
TENSOR=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [17]:
#create a random tensor of size (3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.1503, 0.6616, 0.8956, 0.8192],
        [0.9545, 0.4552, 0.3578, 0.9633],
        [0.0621, 0.4431, 0.1958, 0.9951]])

In [18]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [19]:
#create a tensor of all zeros
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
#create atensor of all ones
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

In [22]:
random_tensor.dtype

torch.float32

In [23]:
#use torch.range()
a=torch.arange(start=1,end=11,step=1)
a

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
#creating a tensors like
ten_zeros=torch.zeros_like(input=a)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatypes

In [25]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,
                             device=None,
                             requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [26]:
float_32_tensor.dtype

torch.float32

In [27]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [29]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [30]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

**getting information from tensors**

In [31]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.8378, 0.4338, 0.2643, 0.5057],
        [0.4913, 0.8646, 0.0744, 0.6870],
        [0.2178, 0.9520, 0.2824, 0.8023]])

In [32]:
some_tensor.size,some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [33]:
some_tensor.size()

torch.Size([3, 4])

In [34]:
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

tensor([[0.8378, 0.4338, 0.2643, 0.5057],
        [0.4913, 0.8646, 0.0744, 0.6870],
        [0.2178, 0.9520, 0.2824, 0.8023]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device tensor is on:cpu


manipulating tensors (tensor operation)

In [35]:
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [36]:
tensor*10

tensor([10, 20, 30])

In [37]:
tensor

tensor([1, 2, 3])

In [38]:
tensor-10


tensor([-9, -8, -7])

In [39]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [40]:
torch.add(tensor,10)

tensor([11, 12, 13])

Matrix multiplication

In [55]:
torch.matmul(torch.rand(10,3),torch.rand(3,10))

tensor([[0.9487, 0.3933, 0.8654, 1.1025, 0.1529, 0.6817, 0.4805, 0.7383, 0.9299,
         0.4441],
        [1.4109, 0.4970, 1.1989, 1.6782, 0.3328, 0.9912, 0.5765, 0.8044, 1.6121,
         0.8288],
        [0.5319, 0.3519, 0.3298, 0.8703, 0.2092, 0.3375, 0.5124, 0.2288, 0.8328,
         0.4621],
        [0.9620, 0.4938, 0.7700, 1.2951, 0.2397, 0.6603, 0.6622, 0.6252, 1.1573,
         0.5967],
        [1.2348, 0.7632, 0.9358, 1.8022, 0.3309, 0.8310, 1.0764, 0.8384, 1.5633,
         0.8131],
        [0.8563, 0.4009, 0.7305, 1.0791, 0.1775, 0.6007, 0.5180, 0.6097, 0.9397,
         0.4693],
        [1.0053, 0.6609, 0.8349, 1.4138, 0.1893, 0.6959, 0.9342, 0.8873, 1.0935,
         0.5322],
        [0.6574, 0.3462, 0.5894, 0.8224, 0.0999, 0.4684, 0.4594, 0.5749, 0.6439,
         0.3028],
        [0.5537, 0.6786, 0.4127, 1.0317, 0.0818, 0.3652, 1.0548, 0.7517, 0.6077,
         0.2773],
        [1.2489, 0.4777, 1.0606, 1.5104, 0.2870, 0.8766, 0.5745, 0.7545, 1.4162,
         0.7236]])

In [56]:
torch.matmul(torch.rand(10,10),torch.rand(10,10)).shape

torch.Size([10, 10])

In [42]:
print(tensor,'*',tensor)
print(f"equals:{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
equals:tensor([1, 4, 9])


In [43]:
torch.matmul(tensor,tensor)

tensor(14)

In [44]:
tensor

tensor([1, 2, 3])

In [45]:
1*1+2*2+3*3

14

In [50]:
tensor@tensor

tensor(14)

In [47]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 3.08 ms, sys: 0 ns, total: 3.08 ms
Wall time: 3.1 ms


In [48]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 103 µs, sys: 0 ns, total: 103 µs
Wall time: 107 µs


tensor(14)

one of the most common errors in deep learning :shape error

In [57]:
tensor_A=torch.tensor([[1,2],
                      [3,4],
                      [5,6]])
tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])
#torch.mm(tensor_A,tensor_B)
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [67]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [58]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [62]:
tensor_B,tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [63]:
tensor_B.T,tensor_B.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([3, 2]))

In [66]:
print(f"original shape:tensor_A={tensor_A.shape},tensor_B={tensor_B.shape}")
print(f"New  shapes:tensor_A={tensor_A.shape} (same shape as above),tensor_B.T={tensor_B.T.shape}")
print(f"Multiplying:{tensor_A.shape}@{tensor_B.T.shape}<-inner dimensions must match")
print("output:\n")
output=torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\noutput shape:{output.shape}")

original shape:tensor_A=torch.Size([3, 2]),tensor_B=torch.Size([3, 2])
New  shapes:tensor_A=torch.Size([3, 2]) (same shape as above),tensor_B.T=torch.Size([2, 3])
Multiplying:torch.Size([3, 2])@torch.Size([2, 3])<-inner dimensions must match
output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

output shape:torch.Size([3, 3])
